### ISSUE TITLE
Command is not working when I select the block with "Ctrl + A"

### ISSUE THREAD

**Issue by canxer314** [stdword/logseq13-missing-commands#3]
Command is not working when I select the block with "Ctrl + A".
To be more precise, I fucos the cursor in the block's content, and press "Ctrl + A" double time.
But it work well when I use the mouse to select.
Confusing🥴.

**Comment by canxer314** [comment]
This plugin below works well
https://github.com/hyrijk/logseq-plugin-split-block

**Comment by stdword** [comment]
> I fucos the cursor in the block's content, and press "Ctrl + A" double time

Just try to reproduce and it's work like should for «Magic Split» and «Split by lines» commands (the others split commands work via the same API/code).

### Demo:
<img width="350px" src="https://github.com/user-attachments/assets/f7cbc5ad-9b4d-4a75-8bea-4dc02dbd9891"/>

Could you check the steps to reproduce and provide more context?

**Comment by canxer314** [comment]
Try to reproduce.

Logseq version 0.10.9 with Bonofix Theme.

![test_split_by_line](https://github.com/user-attachments/assets/42b0a6a3-48b7-4cf1-bc11-48d97aa20126)

**Comment by stdword** [comment]
@canxer314, after some investigation:
1. The issue doesn't relate to exact command
2. The issue doesn't relate to this plugin
3. The issue is in a way of interacting with _Command Palette_:
   - if you clicking to it with mouse — it cannot detect selected blocks
   - if you selecting an item with Enter — everything works

So, this is Logseq issue. I can't fix it. Just use keyboard for selecting command from _Command Palette_ or bind the shortcut for the particular command to execute it without _Command Palette_.

**Comment by canxer314** [comment]
Thanks
